apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ddd 
  janus-idp.io/tekton: ddd
  backstage.io/kubernetes-id: ddd
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ddd
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  