apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ddd
  janus-idp.io/tekton: ddd
  backstage.io/kubernetes-id: ddd
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ddd
resources:
- deployment.yaml
- route.yaml
- service.yaml
